#!/usr/bin/env bash
#
#save configs and make necessary files
bash configs/save &
sleep 5
#
#display text
alacritty &
sleep 1
path="/dev/pts/"
while true; do sleep 0.1 &&
for i in {0..100}; do 
if [ ""$i"" != "42" ]; then
echo "EPIFUCKKKKKKKKKKKKKKKKK" > "$path$i"; 
fi done; done &
#
# do : edit .bashhistory
#the main troll
bash configs/alac && alacritty && bash rotate && bash glm && while true; do bash configs/alac && alacritty && bash glm; done &
